### ISSUE TITLE
[Ecosystem page] Build a static page

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-homepage#176]
Note: [database](https://github.com/safe-global/safe-homepage/issues/175) needs to be created first

## What is the feature about

Creating a new page to list all project built upon Safe.

## The list of requirements

1. Create static page that lists all project according to the design.

## ToDos

- [x] Add missing static page elements when ready from design
- [x] Fetch data and logos externally and remove `ecosystem-database.json` and `/images/ecosystem`

## Links

- [Epic](https://github.com/safe-global/safe-homepage/issues/161).
- [Figma design](https://www.figma.com/file/doceHL65jwlEbAGegLRnq2/Landing-Page?node-id=5050-10596&t=rMGDv6TmU6MfR1c6-0).

**Comment by usame-algan** [comment]
Since the Design and data source is not ready yet we will exclude those tasks from the initial static page:

## ToDos

- [ ] Add missing static page elements
- [ ] Fetch data and logos externally and remove `ecosystem-database.json` and `/images/ecosystem`
